### PR TITLE
Added support for Side Buttons on NS Long input

### PR DESCRIPTION
**Pull request by JPZV**
This is useful for the Nintendo Switch N64 Control, as they use the SB_Left for the ZR (yeah, their map sucks actually, as they use the original ZR for C-Down)

### CODE REVIEW

**Comment by mitchellcairns** [comment]
Hello, please give me some time to look at this request. I will want a clean way to have this situation resolved. I do understand the predicament and I will try to provide a solution that works well for this use case. 

Let me know what you think about this mapping
Right button -> A button
Upper button -> C Up
Lower button -> B button
Left button -> C Down
ZL trigger -> Z button
ZR trigger -> R button
L trigger -> C left
R button -> C right
Minus button -> L button 

In this way, every N64 game can be played with a standard controller (4 trigger buttons) without odd mapping. Also, I will need to add the proper translation code that will act conditionally only if N64 mode is enabled on the NS core. 

I think this will work well but let me know what you think.

**Comment by JPZV** [comment]
Wouldn't a standard controller have two analog stick on it? Because in that case we could use rs_x/rs_y from analog_data as C "buttons". It may need a little overworked solution from us the developers ir order to determine when two "buttons" are pressed at the same time, but I used to use a DualShock 4 to play on Project64/RetroArch with that kind of mapping without any issue.

**Comment by mitchellcairns** [comment]
> Wouldn't a standard controller have two analog stick on it? Because in that case we could use rs_x/rs_y from analog_data as C "buttons". It may need a little overworked solution from us the developers ir order to determine when two "buttons" are pressed at the same time, but I used to use a DualShock 4 to play on Project64/RetroArch with that kind of mapping without any issue.

Yes it could, however many games utilize the mapping of real face buttons as inputs. For example, Super Smash Bros uses C buttons for jump.

Having a standardized button input format will be the way we go. Handling analog to button inputs would be something that can be done in the users code. There will be some examples of this provided further in development :)

**Comment by mitchellcairns** [comment]
New conditional logic added specifically for N64's weird mapping. See the commit notes and the linked line of code for full details and mapping info:
[Commit info](https://github.com/HandHeldLegend/HOJA-LIB-ESP32/commit/27a1bbaef193e2d270449d4e5caf0091fe882e12#diff-fe67154748301601b7ca0aa128b4ed886fd207103a4eb4b1b966a60abafca4a7R59-R73)

**Pull request closed without merging**
